// Generated by CoffeeScript 1.6.3
var canvas, circle1, dataArray, height, width;

dataArray = [70, 60, 50, 40, 30, 20];

width = 600;

height = 600;

canvas = d3.select("body").append("svg").attr("width", width).attr("height", height);

circle1 = canvas.append("circle").attr("cx", 50).attr("cy", 100).attr("r", 25);

circle1.transition().attr("cx", 200);

/*bars = canvas.selectAll("rect")
.data(dataArray)
.enter()
.append("rect")
.attr("width", 50)
.attr("height", (d) ->
	d*10)
.attr("fill", (d) ->
	d)
.attr("x", (d, i) ->
	i * 100)
*/

