// Generated by CoffeeScript 1.6.3
d3.json("data/D3graph.json", function(data) {
  var canvas;
  canvas = d3.select("body").append("svg").attr("width", 1000).attr("height", 1000);
  canvas.selectAll("rect").data(data.graphDetails).enter().append("rect").attr("width", function(d) {
    return d.overall * 10;
  }).attr("height", 45).attr("y", function(d, i) {
    return i * 50;
  }).attr("fill", "blue");
  return canvas.selectAll("text").data(data.graphDetails).enter().append("text").attr("fill", "white").attr("y", function(d, i) {
    return i * 50 + 24;
  }).text(function(d) {
    return d.year;
  });
});
