// Generated by CoffeeScript 1.4.0

d3.json("data/D3graph.json", function(data) {
  var canvas, color, widthScale, yaxis;
  widthScale = d3.scale.linear().domain([0, 75]).range([0, 500]);
  yaxis = d3.svg.axis().scale(widthScale).orient(["top"]);
  color = d3.scale.linear().domain([0, 75]).range(["red", "blue"]);
  canvas = d3.select(".bargraph").append("svg").attr("width", 500).attr("height", 500).append("g").attr("transform", "translate(100,500) rotate(270)");
  canvas.selectAll("rect").data(data.graphDetails).enter().append("rect").attr("class", "vertbargraph").attr("id", "vertBar").attr("width", function(d) {
    return d.overall * 5;
  }).attr("height", 45).attr("y", function(d, i) {
    return i * 70;
  }).attr("fill", "blue");
  canvas.selectAll("text").data(data.graphDetails).enter().append("text").attr("fill", "black").attr("y", function(d, i) {
    return i * 70;
  }).text(function(d) {
    return d.year;
  });
  canvas.append("g").attr("transform", "translate(0,0)").call(yaxis);
  return canvas.selectAll("rect").attr("id", "vertBar").on('click', function() {
    $('.bargraph').hide();
    return $('.sunBurst').show();
  });
});
